# Generated by Django 2.2.1 on 2019-06-16 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('passwd', models.CharField(max_length=20)),
                ('school', models.CharField(blank=True, max_length=50, null=True)),
                ('nickName', models.CharField(default='newUser', max_length=50)),
                ('mailAddress', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('phoneNumber', models.CharField(max_length=20)),
                ('credit', models.FloatField(default=10)),
                ('jurisdiction', models.CharField(default='1', max_length=1)),
                ('nowJurisdiction', models.CharField(blank=True, max_length=1, null=True)),
            ],
        ),
    ]
